config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'home/index'
  get 'home/about'

  resources :titles, only: %i[index], param: :key
  resources :years, only: %i[index show], param: :key
  resources :instrumentals, only: %i[index show], param: :key
  resources :people, only: %i[index show], param: :key
  resources :songs, only: %i[index show], param: :key do
    get :list_by_date, on: :collection
  end
  resources :albums, only: %i[index show], param: :key
  resources :singles, only: %i[index show], param: :key
  resources :videos, only: %i[index show], param: :key
  resources :companies, only: %i[index show], param: :key
  resources :prefectures, only: %i[index show], param: :key
  resources :halls, only: %i[show], param: :key
  resources :bands, only: %i[index show], param: :key
  resources :concerts, only: %i[index show], param: :key
  resources :books, only: %i[index show], param: :key
  resources :activities, only: %i[index show], param: :key
  resources :references, only: %i[index], param: :key
  resources :youtubes, only: %i[index show], param: :key
  resources :stats, only: %i[index] do
    get :songs_in_concerts, on: :collection
    get :prefectures_concerts_performed, on: :collection
    get :lyrics, on: :collection
    get :musics, on: :collection
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_bottom_link_bar.html.haml
.navigation
  = t 'common.links_for_lists'
  - @links = get_links
  - ctl = request.params[:controller].classify
  - @links.each do |array|
    - paths, klass = array
    - paths.each do |path|
      = button_link controller_path: path, flag: klass.to_s == ctl
  = button_link controller_path: stats_path
.navigation
  .float-left
    = link_to t('common.about'), home_about_path
  .float-right
    &copy;1994-2019 hkob.

app/views/shared/_top_link_bar.html.haml
.navigation
  = normal_link title: t('home.index.title'), controller_path: root_path
  .navigation-list.float-right
    = je_link